name: Trigger Yumemi builds

on:
  workflow_dispatch:

jobs:
  build_release:
    name: Trigger Release builds 🚀
    uses: ./.github/workflows/build_release.yml

  build_legacy:
    name: Trigger Legacy builds 🚀
    uses: ./.github/workflows/build_legacy.yml
